CREATE DATABASE ecommerceDB;
USE ecommerceDB;

CREATE TABLE TB_ADMIN_LOGIN(
ID_ADMIN_LOGIN   INT PRIMARY KEY,
DS_EMAIL         VARCHAR(100),
DS_SENHA         VARCHAR(100)
);

CREATE TABLE TB_CATEGORIA(
ID_CATEGORIA             INT PRIMARY KEY AUTO_INCREMENT,
ID_PRODUTO_CATEGORIA     INT NOT NULL, 
NM_CATEGORIA             VARCHAR(100),
DS_TIPOCAT               VARCHAR(200)
);

CREATE TABLE TB_PRODUTO_CATEGORIA(
ID_PRODUTO_CATEGORIA     INT PRIMARY KEY AUTO_INCREMENT,
ID_CATEGORIA             INT NOT NULL,
ID_PRODUTO               INT NOT NULL
);

CREATE TABLE TB_PRODUTO(
ID_PRODUTO               INT PRIMARY KEY AUTO_INCREMENT,
ID_DEPARTAMENTO          INT NOT NULL,
NM_PRODUTO               VARCHAR(200),
VL_CODIGO_PRODUTO        DECIMAL(5,2),  
VL_DESCONTO              DECIMAL(5,2), 
VL_AVALIACAO             DECIMAL(5,2),
DS_FABRICANTE            VARCHAR(200),
DS_TEMPO_DE_USO          VARCHAR(100),
QTD_ESTOQUE              INT,
DS_CARACTERISTICAS       VARCHAR(500),
DS_INFORMACOES           VARCHAR(500),
DS_DESCRICAO             VARCHAR(500),
DT_GARANTIA              DATE
);

CREATE TABLE TB_DEPARTAMENTO(
ID_DEPARTAMENTO      INT PRIMARY KEY,
NM_DEPARTAMENTO      VARCHAR(50),
IMG_CAPA             BLOB
);

CREATE TABLE TB_PRODUTO_IMAGEM(
ID_PRODUTO_IMAGEM    INT PRIMARY KEY AUTO_INCREMENT,
ID_PRODUTO           INT NOT NULL,
IMG_PRODUTO          BLOB
);

CREATE TABLE TB_USUARIO_FAVORITO(
ID_USUARIO_FAVORITO    INT PRIMARY KEY AUTO_INCREMENT,
ID_USUARIO             INT NOT NULL,
ID_PRODUTO             INT NOT NULL	
);

CREATE TABLE TB_PRODUTO_AVALIACAO(
ID_PRODUTO_AVALIACAO    INT PRIMARY KEY AUTO_INCREMENT,
ID_USUARIO              INT NOT NULL,
ID_PRODUTO              INT NOT NULL,
VL_GERAL                INT,
VL_DESEMPENHO           INT,
VL_ATENDIMENTO          INT,
VL_SATISFACAO           INT
);

CREATE TABLE TB_USUARIO(
ID_USUARIO        INT PRIMARY KEY AUTO_INCREMENT,
ID_LOGIN          INT NOT NULL,
NM_USUARIO        VARCHAR(100),
NM_SOBRENOME      VARCHAR(200),
DS_CPF            VARCHAR(14),
DT_NASCIMENTO     DATE,
DS_GENERO         VARCHAR(100),
DS_EMAIL          VARCHAR(100),
DS_CELULAR        VARCHAR(100),
DS_SENHA          VARCHAR(100)
);

CREATE TABLE TB_LOGIN(
ID_LOGIN         INT PRIMARY KEY AUTO_INCREMENT,
ID_USUARIO       INT NOT NULL
);

CREATE TABLE TB_USUARIO_CARTAO(
ID_USUARIO_CARTAO    INT PRIMARY KEY AUTO_INCREMENT,
ID_USUARIO           INT NOT NULL,
NM_CARTAO            VARCHAR(100),
NR_CARTAO            INT,
DT_VALIDADE          DATE, 
NR_CVV               VARCHAR(3),
DS_CPF               VARCHAR(14),
DT_NASCIMENTO        DATE
);

CREATE TABLE TB_USUARIO_ENDERECO(
ID_USUARIO_ENDERECO      INT PRIMARY KEY AUTO_INCREMENT,
ID_USUARIO               INT NOT NULL,
DS_LOGADOURO             VARCHAR(100),
NR_NUMERO                INT,
NM_BAIRRO                VARCHAR(100),
DS_CEP                   VARCHAR(50),
NM_CIDADE                VARCHAR(300),
NM_ESTADO                VARCHAR(100),
DS_COMPLEMENTO           VARCHAR(100),
DS_CASA                  VARCHAR(9)
);

CREATE TABLE TB_PEDIDO(
ID_PEDIDO                INT PRIMARY KEY AUTO_INCREMENT,
ID_USUARIO               INT NOT NULL,
ID_USUARIO_ENDERECO      INT NOT NULL,
ID_CUPOM                 INT NOT NULL,
DT_PEDIDO                DATETIME,
NR_NOTA_FISCAL           INT,
VL_FRETE                 DECIMAL(2,2),
DS_STATUS                VARCHAR(100),
QTD_PRODUTO              INT
);

CREATE TABLE TB_PEDIDO_ITEM(
ID_PEDIDO_ITEM     INT PRIMARY KEY AUTO_INCREMENT,
ID_PEDIDO          INT NOT NULL,
ID_PRODUTO         INT NOT NULL,
VL_PRODUTO         DECIMAL(5,2),
QTD_PRODUTO        INT 
);

CREATE TABLE TB_CUPOM(
ID_CUPOM         INT PRIMARY KEY AUTO_INCREMENT,
NM_CUPOM         VARCHAR(100),
VL_CUPOM         DECIMAL(3,2),
DT_CADASTRO      DATE,
DT_VENCIMENTO    DATE,
IMG_CUPOM        BLOB
);

CREATE TABLE TB_PIX(
ID_PIX           INT PRIMARY KEY AUTO_INCREMENT,
ID_USUARIO       INT NOT NULL,
DS_CHAVE_PIX     VARCHAR(100)
);